import React from 'react';
import { colors, fontSize, radius, spacing } from '../../theme/theme';

export const styles: Record<string, React.CSSProperties> = {
  label: { color: colors.textSecondary, fontSize: fontSize.sm, fontWeight: 600, marginBottom: spacing.sm, marginTop: spacing.lg },
  hint: { color: colors.textMuted, fontSize: fontSize.xs, marginBottom: spacing.sm },
  modeRow: { display: 'flex', flexDirection: 'row', background: colors.surface, borderRadius: radius.pill, padding: 4, marginBottom: spacing.md },
  modeTab: {
    flex: 1,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    border: 'none',
    background: 'none',
    cursor: 'pointer',
  },
  modeTabActive: { background: colors.accent },
  modeTabLabel: { color: colors.textSecondary, fontWeight: 700, fontSize: fontSize.xs },
  modeTabLabelActive: { color: colors.black },
  input: {
    width: '100%',
    background: colors.surface,
    borderRadius: radius.input,
    padding: spacing.lg,
    color: colors.textPrimary,
    fontSize: fontSize.md,
    border: 'none',
  },
  inputDisabled: { opacity: 0.4 },
  checkboxRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.md,
    gap: spacing.md,
    border: 'none',
    background: 'none',
    padding: 0,
    width: '100%',
    textAlign: 'left',
    cursor: 'pointer',
  },
  checkbox: { width: 20, height: 20, borderRadius: 6, border: `2px solid ${colors.divider}`, flexShrink: 0, boxSizing: 'border-box' },
  checkboxActive: { background: colors.accent, borderColor: colors.accent },
  checkboxLabel: { color: colors.textSecondary, fontSize: fontSize.xs, flex: 1, lineHeight: '16px' },
  chipsRow: { display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md },
  chip: {
    paddingLeft: spacing.lg,
    paddingRight: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderRadius: radius.pill,
    background: colors.surface,
    border: 'none',
    cursor: 'pointer',
  },
  chipActive: { background: colors.accentMuted, border: `1px solid ${colors.accent}` },
  chipLabel: { color: colors.textSecondary, fontWeight: 600, fontSize: fontSize.sm },
  chipLabelActive: { color: colors.accent },
};
