import React from 'react';
import { colors, fontSize, radius, spacing } from '../../theme/theme';

export const styles: Record<string, React.CSSProperties> = {
  pageContent: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100%',
  },
  handleBar: {
    width: 40,
    height: 4,
    borderRadius: 2,
    background: colors.divider,
    margin: `0 auto ${spacing.lg}px`,
  },
  topBar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    background: colors.surface,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarTitle: {
    color: colors.textPrimary,
    fontSize: fontSize.lg,
    fontWeight: 800,
  },
  topBarSpacer: {
    width: 32,
    height: 32,
  },
  dateRow: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: spacing.xl,
  },
  dateButton: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    background: colors.surface,
    borderRadius: radius.pill,
    padding: `${spacing.sm}px ${spacing.lg}px`,
  },
  dateButtonText: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: 600,
  },
  sectionLabel: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: 700,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
  },
  chipsContainer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  previewCard: {
    display: 'flex',
    flexDirection: 'row',
    background: colors.warningMuted,
    borderRadius: radius.input,
    padding: spacing.md,
    marginTop: spacing.lg,
  },
  previewText: {
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    flex: 1,
  },
  categorySelector: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    background: colors.surface,
    borderRadius: radius.input,
    paddingLeft: spacing.lg,
    paddingRight: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
  },
  categorySelectorText: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: fontSize.md,
    fontWeight: 600,
    textAlign: 'left',
  },
  modalBackdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
  },
  modalOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
  },
  modalSheet: {
    position: 'relative',
    background: colors.surfaceAlt,
    borderTopLeftRadius: radius.card,
    borderTopRightRadius: radius.card,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    maxWidth: 720,
    margin: '0 auto',
    width: '100%',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: fontSize.lg,
    fontWeight: 800,
    margin: 0,
  },
  modalList: {
    maxHeight: 320,
    overflowY: 'auto',
  },
  modalRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderBottom: `1px solid ${colors.divider}`,
    width: '100%',
  },
  modalRowLabel: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: fontSize.md,
    fontWeight: 600,
    textAlign: 'left',
  },
  modalInputRow: {
    display: 'flex',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  modalInput: {
    flex: 1,
    background: colors.surface,
    borderRadius: radius.input,
    padding: spacing.md,
    color: colors.textPrimary,
    fontSize: fontSize.md,
    border: 'none',
  },
  modalAddBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 44,
    borderRadius: radius.input,
    background: colors.accent,
  },
  msiRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.xl,
    gap: spacing.md,
  },
  msiLabel: {
    color: colors.textPrimary,
    fontSize: fontSize.md,
    fontWeight: 700,
    margin: 0,
  },
  msiSub: {
    color: colors.textMuted,
    fontSize: fontSize.xs,
    margin: '2px 0 0',
  },
  msiSwitchWrap: {
    position: 'relative',
    display: 'inline-block',
    width: 44,
    height: 26,
    flexShrink: 0,
  },
  msiInput: {
    background: colors.surface,
    borderRadius: radius.input,
    padding: spacing.md,
    color: colors.textPrimary,
    fontSize: fontSize.md,
    marginTop: spacing.md,
    width: '100%',
  },
  bottomActions: {
    display: 'flex',
    flexDirection: 'row',
    gap: spacing.md,
    paddingTop: spacing.lg,
  },
};

export const dynamicStyles = {
  chip: (active: boolean): React.CSSProperties => ({
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderRadius: radius.pill,
    background: active ? colors.accentMuted : colors.surface,
    border: active ? `1px solid ${colors.accent}` : 'none',
  }),
  msiSwitchTrack: (isMsi: boolean): React.CSSProperties => ({
    position: 'absolute',
    inset: 0,
    background: isMsi ? colors.accent : colors.divider,
    borderRadius: radius.pill,
    transition: 'background 0.15s',
    cursor: 'pointer',
    pointerEvents: 'none',
  }),
  msiSwitchThumb: (isMsi: boolean): React.CSSProperties => ({
    position: 'absolute',
    top: 3,
    left: isMsi ? 21 : 3,
    width: 20,
    height: 20,
    borderRadius: '50%',
    background: colors.white,
    transition: 'left 0.15s',
    pointerEvents: 'none',
  }),
};
